### ISSUE TITLE
Dual Barcodes

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#148]
Add dual barcode support for Qiime2 to mmeds

**Comment by DSWallach** [comment]
This will involve modifying several parts of the code base

- mmeds/server.py: Add a dual barcodes drop down menu when uploading data
- mmeds/validate.py: Allow BarcodeSequenceR and BarcodeSequenceL as alternatives to BarcodeSequence when checking for required columns. Do the same for LinkerPrimerSequence
-mmeds/Qiime2.py: Add commands for importing and demultiplexing sequences with dual barcodes
-sql/tables.sql: Add a field BarcodeSequence2 to RawData, it would be the reverse read when there are dual barcodes and left blank when there aren't

**Comment by mstapylton** [comment]
for reference when editing Qiime2.py:
https://docs.qiime2.org/2019.4/plugins/available/cutadapt/demux-paired/

**Comment by DSWallach** [comment]
> 

`qiime tools import --type MultiplexedPairedEndBarcodeInSequence --input-path data_files --output-path qiime_artifact_new.qza`
qiime cutadapt demux-paired --i-seqs qiime_artifact_new.qza --m-forward-barcodes-file `Full_Specimen.tsv\
    --m-forward-barcodes-column BarcodeSequenceF --m-reverse-barcodes-file Full_Specimen.tsv\
    --m-reverse-barcodes-column BarcodeSequenceR --o-per-sample-sequences demuxed.qza\
    --o-untrimmed-sequences unmatched_demuxed.qza`
`qiime demux summarize --i-data $RUN_Qiime2_0/demuxed.qza --o-visualization $RUN_Qiime2_0/demux_viz.qzv;`
`qiime dada2 denoise-paired --i-demultiplexed-seqs $RUN_Qiime2_0/demuxed.qza --p-trim-left-f 0 --p-trim-left-r 0 --p-trunc-len-f 0 --p-trunc-len-r 0 --o-representative-sequences $RUN_Qiime2_0/rep_seqs_dada2.qza --o-table $RUN_Qiime2_0/table_dada2.qza --o-denoising-stats $RUN_Qiime2_0/stats_dada2.qza --p-n-threads 2;`
`qiime metadata tabulate --m-input-file $RUN_Qiime2_0/stats_dada2.qza --o-visualization $RUN_Qiime2_0/stats_dada2_visual.qzv;`

An example of the commands as they should look in the final script produced by MMEDS. It seems that the commands from `demux summarize` onwards can remain unchanged from their current implementation for paired end reads

**Comment by DSWallach** [comment]
Here is the updated version of the command
[commands.txt](https://github.com/clemente-lab/mmeds-meta/files/3912497/commands.txt)
