### ISSUE TITLE
PiCRUSt

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#150]
Setup a class for PiCRUSt, inheriting from mmeds/tool.py:Tool
https://picrust.github.io/picrust/

**Comment by cleme** [comment]
PiCRUSt 1 uses an older version of the biom format and of Python, which will result in problems to integrate with MMEDS. PiCRUSt 2 is out as a pre-print (https://www.biorxiv.org/content/10.1101/672295v1) but the code might still undergo changes as it is still in beta (https://github.com/picrust/picrust2). I would suggest giving this lower priority than #151 and #152 as those tools are stable and not likely to change in the short term.

**Comment by cleme** [comment]
To consider: scripts for calculating accuracy of PICRUST 1 require a number of additional files that might not be in the main repo and need to be downloaded separately.

**Comment by DSWallach** [comment]
While working with Sabrina on getting it setup I saw there was a `download_picrust_file.py` script that needed to be run after installing it. Is this what you're referring to? I think it only needs to be done once and so could just be part of setting up the module on chimera

**Comment by cleme** [comment]
Yes, that is part of it: what I've recommended her is to run that manually for now, and see if we can get the accuracy scores calculated that way. If that works, we'll get her notes to replicate analysis through MMEDS.
