### ISSUE TITLE
Upload files to NDA

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#172]
**Is your feature request related to a problem? Please describe.**
Uploading data is annoying
**Describe the solution you'd like**
MMEDs should be able to automate the upload of data files. Creating the required csv from a MMEDS metadata file.
**Describe alternatives you've considered**

**Additional context**
https://github.com/NDAR/nda-tools
https://nda.nih.gov/tools/nda-tools.html#vt
https://nda.nih.gov/data_structure.html?short_name=genomics_sample03
https://nda.nih.gov/contribute/harmonization-standards.html#omics

**Comment by adamcantor22** [comment]
This has been super-ceded by other issues and solutions
