### ISSUE TITLE
Cookies Warning

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#193]
Cookies acceptance warning so we aren't sued

**Comment by adamcantor22** [comment]
This has been implemented using the template here https://html-online.com/articles/cookie-warning-widget-with-javascript/ as a starting point. Clicking 'more info' currently links to https://site.ieee.org/gdpr/digital-guidelines/cookie-compliance/. This should be enough, but we might want to have 'more info' link to a description of the cookies we collect.
