### ISSUE TITLE
Setup SparCC module

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#229]
Setup a SparCC module to use on Minerva

**Comment by DSWallach** [comment]
Sparcc locally is cureently generating the covariance matrix in the manager's directory (`mmeds-meta/mmeds/host/`). Address this as well

**Comment by adamcantor22** [comment]
We will need to review what is and is not implemented regarding SparCC

**Comment by adamcantor22** [comment]
Marking as on hold until we get a clearer picture of what this encompasses
