### ISSUE TITLE
Ensure study names match

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#234]
Ensure the study name provided when uploading and that in the metadata match. Make study names unique for a single user or all users?

**Comment by cleme** [comment]
I think study names should be unique, in case we want to do a "search by study name" across all studies. When users fill in study names, we should suggest them to pick names that are sufficiently descriptive, e.g. no "microbiome study" but sth like "Evaluating the effect of intervention X in the gut microbiome of patients with condition Y".

**Comment by DSWallach** [comment]
Yeah, long term that's certainly what we want. Short term it will require everyone to modify the metadata files individually during the next demo.
