### ISSUE TITLE
Summary Overhaul

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#247]
The default for upper is `'cor'` which calcluates the correlations between groups, but for some datasets this will cause errors if there are not enough data points for a certain group. Modify to use a safer default e.g.
`
ggpairs(df[,c(1:3)], 
                    upper = list(continuous = "points", combo = "box_no_facet"),
      lower = list(continuous = "points", combo = "dot_no_facet"),
             aes(color = df$GroupID, label = rownames(df), alpha=0.5)) +
         theme_bw() +
         theme(legend.position = 'none',
               plot.title = element_text(hjust = 0.5),
               plot.subtitle = element_text(hjust = 0.5)) +
         labs(title = 'PCA plot',
              subtitle = 'Colored by SpecimenTimepoint')
`

**Comment by DSWallach** [comment]
This should be done if there are not enough samples in a particular group to produce the default statistics

**Comment by DSWallach** [comment]
https://github.com/jupyter/nbconvert/issues/1451
Related to broken summary functionality

**Comment by DSWallach** [comment]
https://github.com/t-makaro/nb_pdf_template
Use this
Also fix the formatting for the level value in the taxa summary

**Comment by DSWallach** [comment]
also add automatic prefixes to column names to allow them to start with numbers in Python

**Comment by DSWallach** [comment]
Taxa_bar_plot not appearing in file index of analyses

**Comment by DSWallach** [comment]
Skip continuous variables for beta group significance. Or automatically create bins

**Comment by DSWallach** [comment]
For taxa tables in francesca's data the id column was labeled 'level_0' rather than 'index' because a different column was 'index'. Add checks to automatically catch this situatio

**Comment by DSWallach** [comment]
The colors are defined starting from color0 but are used starting from color1. This can cause problems

**Comment by adamcantor22** [comment]
Closing, linking in #322
