### ISSUE TITLE
Chrome logs users out when navigating to the upload page

### ISSUE THREAD

**Issue by mstapylton** [clemente-lab/mmeds-meta#282]
**Describe the bug**
User gets logged out when going to the upload page in chrome browser, not present in Firefox browser

**To Reproduce**
1. Start MMEDs, login
2. Select upload from drop down menu
3. Observe that you're logged out

**Expected behavior**
Upload page successfully loads. 

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by mstapylton** [comment]
Couldn't replicate on MMEDs hosted on minerva. Issue still occurs locally after clearing cookies, cached files.

**Comment by adamcantor22** [comment]
Conclusion seems to be that this is not a problem for MMEDS production or for testing on Firefox
