### ISSUE TITLE
Error handling for improperly formatted metadata

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#285]
Handle situation where one of the column rows is missing
Required column have headers that are missing
required columns have headers that are misspelled
Uploaded file is the wrong type
Uploaded file has one extension but is actually a different file type e.g. and xlsx file with a `.csv` extension
Add tests were each row is entirely
- A) Blank
- B) NA's
- C) other values
- D) Numbers
- E) Dates

**Comment by DSWallach** [comment]
Step 1) Update `scripts/generate_test_metadata.py`
Create a script to generate test files where a each column has been replaced by values of the following types
    A) Blank
    B) NA's
    C) other values
    D) Numbers
    E) Dates
write each group of files to a separate directory, sub-divided into a directory for subject files and one for specimen files.
So the output will look like
`blank_column_tests/subject/blank_HostSubjectID.tsv`,
`blank_column_tests/subject/blank_IllnessStartDate.tsv`
.....
`date_column_tests/specimen/date_CollectionDate.tsv`
`date_column_tests/specimen/date_SampleType`

Use `scripts/generate_test_metadata.py` for an example of how to do this type of thing

**Comment by DSWallach** [comment]
Step 2) Create a new file in `mmeds-meta/mmeds/tests/server` to try uploading each of these example files to their appropriate web pages. Use `mmeds-meta/mmeds/tests/server/test_server.py` as an example for how to handle running a test server and uploading files.

**Comment by DSWallach** [comment]
Step 3) Identify and resolve errors that come up during the running of tests.

**Comment by adamcantor22** [comment]
Step 1 complete.

Notes:
-The 'other' values I chose are dictionaries of format {boolean: boolean}
-Number values are random integers between 1 and 2000
-Date values are random YYYY-MM-DD dates from 2015-2025
        -No date has DD higher than 28, to prevent any February strangeness
