### ISSUE TITLE
Improved summaries: demultiplex and table statistics

### ISSUE THREAD

**Issue by cleme** [clemente-lab/mmeds-meta#327]
**Is your feature request related to a problem? Please describe.**
Summaries do not include any type of summary statistic on demultiplex and feature table.

**Describe the solution you'd like**
Include text and plots generated from demux and table creation process: min and max number of sequences per sample, histogram of samples/counts, etc.

Links to #322

**Comment by adamcantor22** [comment]
The sections currently go 1.Taxa 2.Alpha 3.Beta, where should this section be inserted?

**Comment by cleme** [comment]
@adamcantor22 what was the decision on this issue? Are demux and table statistics things that we can incorporate for the release?

**Comment by adamcantor22** [comment]
@cleme I don't think so for this release. I don't think there can be a fast implementation for any kind of new feature in the summaries at the moment.

**Comment by cleme** [comment]
Ok, let's prioritize: bugs obviously need to go first, if we finish those on time then we'll consider including this in the release. So we'll keep it for now and make a final decision closer to the deadline.
