### ISSUE TITLE
Improved summaries: fix continuous variables

### ISSUE THREAD

**Issue by adamcantor22** [clemente-lab/mmeds-meta#339]
**Is your feature request related to a problem? Please describe.**
Continuous variables do not mix well with our summaries. Either their plots don't show up at all, or their legends don't appear, or the legends pose a serious readability problem.

**Describe the solution you'd like**
Plots show consistently sorted by continuous variables. Split continuous variables into 'continuous' and 'semi-continuous'. Both should be colored on a gradient, but fully continuous variables should be expressed in the legend as a horizontal bar that contains the gradient, whereas semi-continuous variables can be expressed like categorical variables in the legend. A semi-continuous variable becomes fully continuous when it has over N unique values, where N is maybe 10 or 20.

**Comment by adamcantor22** [comment]
Not having this poses a serious threat to our ability to reliably produce results. In trying to produce a summary for Alison's GRAPHS study 'gut_children_only', there are several conditions that cause the jupyter nbconvert command to completely fail. These have not been tested to confirm, but it seems the additional problems occur in continuous variables when:
- Any of the entries are 'nan' (most confident this is the case)
- Any of the values are negative
- Some entries are whole numbers, others are not (least confident this is the case)

**Comment by adamcantor22** [comment]
Link to example jupyter notebook, based on the study in above comment:
https://drive.google.com/file/d/1zs1Qpxvbkts6lk_Y3JtShx8n0ZPqIvha/view?usp=sharing

**Comment by cleme** [comment]
@adamcantor22 the environment setup requires a file called `environment.yml` (https://github.com/clemente-lab/mmeds-meta/blob/master/docs/summary_env.md) that is not in Drive.

**Comment by cleme** [comment]
Also, which is the first cell in the notebook that results in an incorrect plot or a missing legend?

**Comment by adamcantor22** [comment]
@cleme 
environment.yml: https://github.com/clemente-lab/mmeds-meta/blob/master/docs/environment.yml

First plot in the notebook that causes an error should be cell 32, the R code for generating the taxa plot grouped by Age

**Comment by cleme** [comment]
@adamcantor22 first suggestion to narrow this down: can you generate the DF that is being loaded in that cell 32 and save it to a file? So, run all the cells yourself, then save the DF to a CSV or pickle, and then share the DF file in the Google Drive folder.

That would simplify debugging, as we would only have to start a new notebook, load the DF and then try the command on that cell without having to go through the extensive setup that the full notebook requires.

**Comment by adamcantor22** [comment]
@cleme Done! It's in the google drive folder as `premade_df.csv`. Run `pd.read_csv('premade_df.csv')` to get it, no other arguments needed.

**Comment by cleme** [comment]
@adamcantor22 R seems to be loading the data correctly:

```
> df <- read.table('/Users/cleme/Downloads/premade_df.csv',header=TRUE,sep=',')
> head(df)
   variable                      X.OTU.ID
1 BM0016C_F   k__Archaea;p__Euryarchaeota
2 BM0016C_F                k__Bacteria;__
3 BM0016C_F k__Bacteria;p__Actinobacteria
4 BM0016C_F  k__Bacteria;p__Bacteroidetes
5 BM0016C_F  k__Bacteria;p__Cyanobacteria
6 BM0016C_F     k__Bacteria;p__Firmicutes
         value      Age
1 0.0031353579 4.512329
2 0.0010749798 4.512329
3 0.0559885335 4.512329
4 0.0159455344 4.512329
5 0.0005374899 4.512329
6 0.9113141629 4.512329
> typeof(df$variable)
[1] "character"
> typeof(df$X.OTU.ID)
[1] "character"
> typeof(df$value)
[1] "double"
> typeof(df$Age)
[1] "double"
```

can you test the same thing I'm doing above (`typeof`) from the notebook? So:

```
df <- pd.read_csv('premade_df.csv')
%%R -i df
typeof(df$variable)
...
```

does the result match what I'm getting from R directly?

**Comment by cleme** [comment]
@adamcantor22 Never mind: the issue is obviously in the original R code. This:

`     facet_grid(~Age, scales = "free", space = "free") +`

cannot work because `Age` is a continuous variable, and `facet_grid` works with discrete variables.

So at least this particular case is solved: it doesn't work because it should *not* work. The solution is: in cases were the variable is continuous, this plot should not be calculated.

Please post some other example of a plot that does not work with continuous variables, and do the same as we've done here: get the DF in a file, so I can run it directly in R to test.
