### ISSUE TITLE
Fix Animal study uploading

### ISSUE THREAD

**Issue by adamcantor22** [clemente-lab/mmeds-meta#347]
**Describe the bug**
There has not been an animal study in some time, and code pushed to master since then has broken the upload process, mostly due to looking for specific human metadata columns that don't exist or are called something different in animal studies.

**To Reproduce**
Use the `test_animal` subject and metadata files in an upload marked as 'Animal'

**Expected behavior**
Upload should proceed as normal

**Comment by adamcantor22** [comment]
Amaia's study can't be run until this issue is resolved

**Comment by cleme** [comment]
Moving this to 0.7 release, since this is a bug that (maybe) can be addressed in time.
