### ISSUE TITLE
Streamline creating summary environment and necessary setup / improve ability to run in different environments

### ISSUE THREAD

**Issue by mstapylton** [clemente-lab/mmeds-meta#349]
**Describe the bug**
Setting up the environment for running summaries via `scripts/summarize.py` is proving difficult and fairly environment dependant. Environment issues for running the summaries aren't easy to troubleshoot either, have seen some weird behavior in my setup. Additionally, summaries aren't working on minerva where we'd ideally like to be running them due to package inconsistencies / updates rolled out by HPC.

**To Reproduce**
1. Follow set up instructions in: docs/summary_env.md
2. Make sure you're on the branch Enhancement-SummaryImprovement
3. run `python scripts/summarize.py on a completed MMEDs analysis directory`

**Expected behavior**
Summaries run without error.

**Comment by cleme** [comment]
I am going to label this as a bug since @mstapylton is still not able to run summaries locally (minerva is a different beast and deserves its own issue).

**Comment by cleme** [comment]
@mstapylton any luck with this? It would be useful to see what issues exactly do you have, so others can try to replicate.

**Comment by mstapylton** [comment]
addressed in https://github.com/clemente-lab/mmeds-meta/pull/368
