### ISSUE TITLE
LEfSe analysis

### ISSUE THREAD

**Issue by cleme** [clemente-lab/mmeds-meta#354]
**Is your feature request related to a problem? Please describe.**
Incorporate LEfSe analysis to MMEDS results.

**Describe the solution you'd like**
Use command-line version in minerva. We should review what is current version.

**Comment by adamcantor22** [comment]
There is a question of whether LEfSe plots should be included in summaries or not.

**Comment by cleme** [comment]
They should eventually be included: the question is whether we simply include them "as is" for 0.8 or we write some code to fit them into a page (so: if plot is too large, we remove some of the less differential taxa, so the final plot fits in a page). TBD.

**Comment by adamcantor22** [comment]
There's a question that's come up regarding how LEfSe tables are formatted. They need to be in a slightly annoying configuration, with the desired metadata columns added as rows to the top of the ASV table. It's not hard to do with a script, but talking with Hilary and Alba revealed that everyone has their own way of doing that formatting. It would be good to standardize that. So the question is: should that formatting script be part of MMEDS, or should it be something more accessible to the whole lab (labtools, anapi, etc) that MMEDS pulls from?

**Comment by cleme** [comment]
This is the type of thing that biobubble was initially thought for. Since we are currently not making any progress on that, I suggest you incorporate the code as part of the wrapper/plugin system for MMEDS to interact with external tools. Eventually this code should be refactored to biobubble so that everybody is using the same approach to handle and parse LEfSe tables.
