### ISSUE TITLE
PICRUST analysis

### ISSUE THREAD

**Issue by cleme** [clemente-lab/mmeds-meta#355]
**Is your feature request related to a problem? Please describe.**
Incorporate PICRUSt analysis into MMEDS.

**Describe the solution you'd like**
Use PICRUSt 2.0 to predict function. TBD what type of sub-analyses should be performed on the predictions (if any, for this issue).

Assigning @mstapylton for now since he recently managed to run PICRUSt 2 on a set of samples analyzed through Q2.

**Comment by mstapylton** [comment]
I ran into this too, my script that ran picrust2 is here:
/sc/arion/projects/CVDlung/cerutti-lab/picrust2/code/run_picrust.lsf

**Comment by adamcantor22** [comment]
I solved the issues I was having, and just ended up submitting the jobs with `picrust2_pipeline.py`. Could you post `run_picrust.lsf`, though? I don't have access to that project directory.

**Comment by mstapylton** [comment]
I used picrust2_pipeline.py too, had to create my own picrust environment. Just thought maybe the script would be useful as an example

**Comment by adamcantor22** [comment]
Consider this issue https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-categorize_by_functionpy-like-in-picrust1
