### ISSUE TITLE
hanging pdflatex command

### ISSUE THREAD

**Issue by adamcantor22** [clemente-lab/mmeds-meta#357]
**Describe the bug**
The `pdflatex` command that gets run after the `jupyter nbconvert` command sometimes hangs when being run automatically. When it is run through `summarize.py`, there is no indication that anything is wrong, but the process will remain on pdflatex when the command should only take a few seconds. When that command is KeyboardInterrupted, and `pdflatex` is run manually on the .tex file, we get output that looks like this:
![Screenshot from 2021-12-07 13-15-18](https://user-images.githubusercontent.com/11340232/145085380-64d866cb-8a51-4268-a4cf-3963dad53f7a.png)

At this point it waits for user input, and pressing Enter will move to the next error. All the errors seem to be the same. In Serre-Yu's data, the lines that latex takes issue with is in this block (specifically line 500):
![Screenshot from 2021-12-07 13-19-51](https://user-images.githubusercontent.com/11340232/145085664-853a9370-395c-4e25-b594-707c29d369b2.png)

This code block appears frequently in the latex file, across every metadata variable. However, in this (Serre-Yu's) case, it is only `Weight` that is causing the issue. This is strange, as `Weight` is not the only continuous variable in the bunch. For example, `IllnessStartDate` is also a continuous variable in this data, but does not throw errors. Here is its corresponding code block:
![Screenshot from 2021-12-07 13-20-19](https://user-images.githubusercontent.com/11340232/145086005-ae6e4eb0-df3c-4c82-92ce-4a66c6eb28e7.png)

And here are legends for both `Weight` and `IllnessStartDate`:
![Screenshot from 2021-12-07 13-21-38](https://user-images.githubusercontent.com/11340232/145086142-6724fb16-6373-4848-9d25-c94874332e29.png)

![Screenshot from 2021-12-07 13-21-53](https://user-images.githubusercontent.com/11340232/145086151-3e89ffa1-8435-4934-9d6b-b8663db625f5.png)

This bug will potentially be fixed upon completion of issue #356 

**Steps to reproduce**
1. Donwload this latex file: https://drive.google.com/file/d/1gEGBv_x6EGpzyJqwQ_zRO_s1LMexi1_U/view?usp=sharing
2. Run `pdflatex latex_file.tex`
3. Press Enter through all the errors

**Comment by adamcantor22** [comment]
It is unclear what causes this to occur on some continuous variables but not others, but it only occurs with continuous variables.

**Comment by adamcantor22** [comment]
For thoroughness, here's the output when i run `pdflatex --versio
![Screenshot from 2021-12-07 13-41-35](https://user-images.githubusercontent.com/11340232/145087613-c8964c34-f05e-4a3f-8ded-5e075a809b8f.png)
n`

**Comment by cleme** [comment]
Is this blocking for 0.7?

**Comment by adamcantor22** [comment]
What do you mean by blocking for 0.7?

**Comment by cleme** [comment]
If pdflatex cannot convert to PDF sometimes, we cannot generate summaries, which means this would is a bug and would prevent us from releasing until solved. Issues that prevent from a release are blocking issues and take highest priority.

**Comment by adamcantor22** [comment]
Ah, I see. Then yes, it is blocking, albeit with an easy manual fix when we’re the ones using it.

**Comment by adamcantor22** [comment]
This is fixed by the solution to #358
