### ISSUE TITLE
Coloring of text in PCOA plots should be independent of coloring of points

### ISSUE THREAD

**Issue by cleme** [clemente-lab/mmeds-meta#360]
**Describe the bug**
In PCOA plots, the color of text with `geom_text_repel()` is currently set to the color of the points that are being labelled. 

**To Reproduce**
Generate summaries of a study. Individual PCOA plots will have labels colored according to the color applied to points.

**Expected behavior**
Label text should have a uniform color.

**Screenshots**
![Screen Shot 2021-12-09 at 10 35 41 AM](https://user-images.githubusercontent.com/1633738/145426742-b431d0f2-da74-4fab-84fe-798cc1e92c06.png)

**Proposed solution**
Change coloring with `geom_text_repel(color="black", alpha=0.6...)` or some other option. Consider if it is more important to have points displayed above text, or text displayed above the points.

**Comment by adamcantor22** [comment]
This is a version with these changes versus the old version. To me, the old version seems much easier to read/understand. @cleme thoughts?
![Screenshot from 2021-12-28 10-16-10](https://user-images.githubusercontent.com/11340232/147580940-b9638499-39fe-4644-85af-43cef6d24111.png)
![Screenshot from 2021-12-28 10-16-56](https://user-images.githubusercontent.com/11340232/147580946-2ecb12bf-8dc3-4795-963d-6d6ca1e77eee.png)

**Comment by cleme** [comment]
Try lowering the alpha value for the text and increasing it for the dots: that would make them more visible compared to the text.

**Comment by adamcantor22** [comment]
Went too far with lowering the text alpha here, but I think this shows the problem is actually stemming from using white as our midpoint on a white background. We should pick a new midpoint color(s) or go back to no midpoint.

![Screenshot from 2021-12-28 15-12-05](https://user-images.githubusercontent.com/11340232/147603548-ccd570b5-769b-429b-ac2a-e2d87ba9c646.png)

**Comment by cleme** [comment]
Agreed. Change palettes to have no white midpoint, since white is background. That should solve the problem of text color.

**Comment by adamcantor22** [comment]
Lmk any further visual tweaks. This is with text `alpha = 0.45`.
![Screenshot from 2022-01-03 09-57-47](https://user-images.githubusercontent.com/11340232/147945705-06152dc4-4066-4280-826f-62f5f1a63890.png)
![Screenshot from 2022-01-03 09-58-01](https://user-images.githubusercontent.com/11340232/147945707-88c709fe-df8f-4b1c-b70f-215c885863f8.png)
![Screenshot from 2022-01-03 09-58-33](https://user-images.githubusercontent.com/11340232/147945708-b89c0b1f-69d6-4343-96b9-792b11b39653.png)
:

**Comment by cleme** [comment]
Good to go.
