### ISSUE TITLE
Integrate correlation analysis in MMEDS through CUTIE

### ISSUE THREAD

**Issue by cleme** [clemente-lab/mmeds-meta#361]
**Is your feature request related to a problem? Please describe.**
Correlation of ASV/taxa abundance vs variables in the mapping file.

**Describe the solution you'd like**
Use CUTIE functionality to perform and integrate correlation analysis.

**Additional context**
This is likely a large issue that needs to be broken down into smaller components. Sub-issues can than be linked to this one.

**Comment by adamcantor22** [comment]
TBD: Include all CUTIE outputs in summaries?
