### ISSUE TITLE
Different palettes for continuous variables

### ISSUE THREAD

**Issue by cleme** [clemente-lab/mmeds-meta#362]
**Is your feature request related to a problem? Please describe.**
Currently, there is a single palette being used for all continuous variables

**Describe the solution you'd like**
Have a number of different palettes for different variables. If there are more continuous variables than pre-defined palettes, coloring would rotate and stat with first palette again.

**Comment by adamcantor22** [comment]
Here are two gradients I've added. I've also made it very simple to add to the list or to let them be used in a specific order, so if there are specific requests for gradients, put them in the comments here.

![Screenshot from 2021-12-28 13-42-36](https://user-images.githubusercontent.com/11340232/147597413-ec24cd3f-3b85-4fc3-b8fc-087502e444c0.png)
![Screenshot from 2021-12-28 13-46-06](https://user-images.githubusercontent.com/11340232/147597416-34d1b8d6-62f3-45f3-a8f2-86591cac3cd3.png)

**Comment by cleme** [comment]
Same comment as in the other issue: we should remove white as midpoint color, since background is white and that can make some lines indistinguishable.

**Comment by adamcantor22** [comment]
Same as other issue

![Screenshot from 2022-01-03 10-00-52](https://user-images.githubusercontent.com/11340232/147945966-0450d7c2-a2d6-430b-aae8-56ad754c39cb.png)
![Screenshot from 2022-01-03 10-01-04](https://user-images.githubusercontent.com/11340232/147945968-8d5abe95-e72d-4e93-a5f4-391897236f89.png)
![Screenshot from 2022-01-03 10-01-19](https://user-images.githubusercontent.com/11340232/147945969-975eb3fd-90a9-4232-8a42-a9a80fd20098.png)

**Comment by cleme** [comment]
This is good too.
