### ISSUE TITLE
Summaries that have only continuous or discrete variables break

### ISSUE THREAD

**Issue by mstapylton** [clemente-lab/mmeds-meta#365]
Summaries that have only continuous or discrete variables break
the code doesn't currently handle those cases, tries to concatenate results that don't exist

the issue is in the mmeds/resources/summary_code.txt

note that part of the problem in fixing this is that summary_code.txt doesn't get updated in the conda env unless build artifacts get removed first. 

**To Reproduce**
1. Go to mmeds install directory
2. activate jupyter environment
3. Run:  `python scripts/summarize.py -p /sc/arion/projects/clemej05a/matt/mmeds/test_Qiime2/Qiime2_0 -t qiime2`

**Expected behavior**
Summary runs succesfully

Observed behavior:
error related to pd.concat()

**Comment by cleme** [comment]
While @mstapylton already has a solution for this, I suggest @adamcantor22 takes a look before we release the patch.
