### ISSUE TITLE
config.py take a yaml configuration file

### ISSUE THREAD

**Issue by mstapylton** [clemente-lab/mmeds-meta#369]
config.py has some bandaid fixes to allow MMEDs to run in different environments. Current workarounds use a combination of the parameters IS_PRODUCTION and TESTING to set MMEDs global variables and control connecting to databases

proposed solution: yaml config file for mmeds that sets these values, maybe even gets passed around. This was Ensemble's solution, and it worked well. Can make debugging easier.

**Comment by cleme** [comment]
Assign issue to a release.

**Comment by adamcantor22** [comment]
outdated
