### ISSUE TITLE
automate testing analyses 

### ISSUE THREAD

**Issue by mstapylton** [clemente-lab/mmeds-meta#370]
We have most of what we need to do this, a minimized conda env for jupyter, code to create the environment through github actions, etc

Need to decide how many different summaries/analyses to test + what conditions. So far we have: all continuous metadata columns, all discrete metadata columns

Also, Ideally want to get pdflatex command working out of a conda environment using texlive/2018

**Comment by cleme** [comment]
To test:
- All continuous metadata.
- All discrete metadata.
- A combination of continuous and discrete metadata.
- Metadata with potential for issues (both in column name and in values): escape characters, slashes, percentage signs, underscores, caret, hash, NULL, NA, blanks, etc.
