### ISSUE TITLE
Analysis type should default to dada2

### ISSUE THREAD

**Issue by mstapylton** [clemente-lab/mmeds-meta#384]
Currently when starting a new analysis, the dropdown default is qiime1 analysis. It strikes me this should be changed to dada2 or maybe deblur?

**Comment by adamcantor22** [comment]
Have we discussed removing support for qiime1 analysis? Of course qiime1 has some useful functionality, but it's gone un-updated for so long I'm guessing it would fail if we tried to run it at this point.

**Comment by adamcantor22** [comment]
this is a very simple fix (just changing the default in the html file), so taking off hold and adding to 0.8.0

**Comment by cleme** [comment]
On the topic of dropping support for Q1: some of the old functionality still does not exist elsewhere, so although we'll eventually remove Q1, for the time being we'll keep it just in case.
