### ISSUE TITLE
MMEDS Data Restructuring

### ISSUE THREAD

**Issue by adamcantor22** [clemente-lab/mmeds-meta#385]
**Is your feature request related to a problem? Please describe.**
Currently, all study directories on minerva contain the entirety of the sequencing run that they are using. This is data-ineffecient, and prevents expansion of the n:n relationship between studies and sequencing runs. This issue represents the "home page" for all issues related to the current restructuring of MMEDS and meta-analysis.

**Describe the solution you'd like**
We need to separate the sequencing runs into their own separate folder, remove the redundancy, and replace the sequencing run data that was inside the study directories with symbolic links to their sequencing run directory.

**Additional context**
This will involve a lot of work, including syncing the schema, databases, and file structures in minerva

**Comment by cleme** [comment]
This is related to issues #371 #353 #352 #337 and #231, and needs to be addressed first to ensure those other issues can be resolved.

**Comment by adamcantor22** [comment]
We need to go over (and get info from David) what exactly the role of SQL and MongoDB are playing in MMEDS, because it is not currently clear to us.

**Comment by cleme** [comment]
This information should be stored as developer notes. We should have a MMEDS website for user documentation, one for developers.

**Comment by adamcantor22** [comment]
One of the biggest problems we will encounter are in the files `database/database.py` and `database/metadata_uploader.py`. The purpose of these files is to *jointly* upload a study and a sequencing run to the database. It may be necessary to completely rework these files.

**Comment by adamcantor22** [comment]
General update on this: started by trying to modify the class `MetaDataUploader` into a format that could accept both sequencing runs and studies, but the class is so structured for studies that this ended up being too difficult, causing many errors and requiring a lot of unclear logic. So the new solution is a new class, `DataUploader` (name subject to change), that is built specifically for sequencing runs. These two classes share a lot of logic, so after the structure is finalized, we may want to create a parent class for both of them (`Uploader`, perhaps) in order to reduce repetition between the two and generally follow some better OOP practices.

**Comment by cleme** [comment]
This reads like a good solution, agree having separate classes for now and then later creating a parent is probably the way to go.

**Comment by cleme** [comment]
What is the purpose of `RawDataProtocolID`, to indicate the run ID? If so, then I think it makes sense we use that. *Generally* sequencing centers provide unique IDs for their runs, I think NYU uses sth like `PIname_MSQ_dd` or something like that for the directories in which they store the results. So I think that solution is simple enough.

**Comment by adamcantor22** [comment]
We discussed `RawDataProtocolID` in our last issue meeting, the gist of it is in my second comment in #337. Currently, that column is one of a couple that exist where you need to provide a unique value in each row (so it usually goes 'Protocol1', 'Protocol2', etc.) and I think it's to link the different tables of the schema together. But yes, I agree that it makes sense to just use that. I was just thinking about Option 2 in terms of some more user-proof functionality that could result in fewer errors, but it doesn't actually seem that necessary.

**Comment by cleme** [comment]
Simpler solution is better, as Occam would argue. `RawDataProtocolID` it is, unless there is something I am missing.

**Comment by adamcantor22** [comment]
As with the above comments, users will now need to put the exact names of the sequencing runs they will be using into their metadata files. So, there needs to be a place where users can see all the sequencing runs they've uploaded (and maybe stats on how many analyses it's been used in), as there is currently with studies. This could be an entirely new tab, or we could add it to the 'Studies' tab (and then possibly rename that tab). Any preference @cleme ?

**Comment by cleme** [comment]
UI needs to be redesigned anyways, probably for 1.0. Whatever it is easier for you right now.

Think though that a user might not have control over the sequencing run. For example, MTC studies are "run" by the core but analysis is performed by the user (which right now means us, but ideally not so in the future). So I think the user needs to be aware of the sequencing info *before* any data/metadata is uploaded to MMEDS, although it would be useful for users to know in MMEDS (through e.g. a tab) which sequencing runs contain their data.

On this topic, it's also important to start considering potential issues with ownership of analysis/sequencing runs. As in the example above, runs might not "belong" to a user who is performing analysis. Also runs can be shared across multiple studies, which complicates things a bit more. The easiest solution for now is probably to have MMEDS admin own all runs and analyses just so users don't mess up things.

**Comment by cleme** [comment]
For MTC studies, I think part of the problem is easily solved since Ilaria knows the sequencing run name and helps with templates, btw.

**Comment by adamcantor22** [comment]
Well, the solution might be to use the 'public' flag that theoretically allows any users to use that data, but I believe that needs to be fleshed out more. Maybe eventually we could have some method by which a user can share a sequencing run/study specifically with one user/set of users if they don't want the data to be public.

For now, though, it's easy enough for me to own all the runs and analyses. If someone else wants to run analysis (@mstapylton ) they'll have to upload the sequencing runs from their account to use until we come up with this fix, as it has been. Still, in our current conditions, uploading a sequencing run per-user is more efficient than doing it per-study.

**Comment by cleme** [comment]
'public' is not intended for that, some studies (most studies) are not made public until published for multiple reasons. TBD, but data/metadata ownership requires its own issue.

Agree it would be good to have a solution where it's not just you owning everything. Unless by "you" you mean MMEDS admin account, if that's what you meant then I think this is a reasonable temporal solution.

**Comment by cleme** [comment]
Ok, so then this is all a bit more complicated. Suggest for now you keep a solution that works (but do not flag all studies as 'public') and open a new issue on ownership to be tackled at 1.0.

**Comment by adamcantor22** [comment]
Next steps as discussed in our meeting:
- Improve storage structure of sequencing runs so it is easy to tell which file is which
- Reconsider symbolic links and where in upload/analysis directory they should go
- Add sub-analysis directories for each demux/denoise run in an analysis
- Serialize demux/denoise runs into main job pipeline
