### ISSUE TITLE
Investigate LEfSe normalization

### ISSUE THREAD

**Issue by adamcantor22** [clemente-lab/mmeds-meta#424]
**Describe the bug**
We currently use a normalization value of 1,000,000 for running LEfSe, but it's not clear where this value comes from, other than Jose using it at one point. Need to investigate and figure out if this is the desired value.

**Comment by cleme** [comment]
The value was used in the original LEfSe tutorial, which does not seem to be online anymore. For now maybe keep this as a parameter with default value of 1M, but consider testing on a couple of datasets how much results differ if we set it to the current LEfSe default value.

**Comment by cleme** [comment]
Also, this is not a bug: that label should be reserved for issues that break the code.

**Comment by adamcantor22** [comment]
![image](https://user-images.githubusercontent.com/11340232/192067332-b6a01dc3-5849-4d11-8524-eb5a7f0bc6f9.png)
Galaxy has this as a default, recommends it when low values present
