### ISSUE TITLE
Add filtered warning

### ISSUE THREAD

**Issue by DSWallach** [clemente-lab/mmeds-meta#83]
Add warning telling the user how many samples (and the percentage) that were 
filtered out prior to the analysis

**Comment by adamcantor22** [comment]
@cleme 'filtered out prior to the analysis' I'm not sure what step David meant here, is this about the creation of `filtered_table.qza` during the analysis, or something else?

**Comment by cleme** [comment]
Unclear. But it is something we want to provide to users in the summary: basic statistics at the beginning of the report. E.g. total initial samples = X; samples after demultiplex = X - a; samples after ASV table construction = X - a - b; etc.

**Comment by adamcantor22** [comment]
Made obsolete by #327
